name: "CI"
on:
  push:
    branches:
      - 'master'


jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: "Check out the code"
        uses: actions/checkout@master

      - name: "Set up Java"
        uses: actions/setup-java@master
        with:
          distribution: 'zulu'
          java-version: 11

      - name: "Build and upload site to Google Storage bucket"
        env:
          gcloudServiceAccountKey: ${{secrets.CLOUD_RUN_DEPLOY_ALTER_REBBE}}
        run: ./gradlew --no-daemon --console=plain uploadSite

      - name: "Notify the Cloud Run service"
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://www.alter-rebbe.org/reset-cached-site'
          method: 'GET'
          preventFailureOnNoResponse: 'true'
